language: python
python:
  - 2.7
install:
  - sudo apt-get install protobuf-compiler
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - ./protoc.sh
  - PYTHONPATH=src coverage run --source=amberdriver setup.py test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a92d0e0a6511230d702b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
